/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RequirementType = IDL.Variant({
  'home' : IDL.Null,
  'agriculture' : IDL.Null,
  'industry' : IDL.Null,
});
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'requirementType' : RequirementType,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const SubmitInquiryResult = IDL.Variant({
  'ok' : IDL.Nat,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, RequirementType, IDL.Text],
      [SubmitInquiryResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RequirementType = IDL.Variant({
    'home' : IDL.Null,
    'agriculture' : IDL.Null,
    'industry' : IDL.Null,
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'requirementType' : RequirementType,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SubmitInquiryResult = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  
  return IDL.Service({
    'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, RequirementType, IDL.Text],
        [SubmitInquiryResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };